"""docvault models

Revision ID: 7d5c9bc40367
Revises: 0002
Create Date: 2026-07-08 09:05:45.894911
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '7d5c9bc40367'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bucket',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['company_admin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bucket_company_id'), 'bucket', ['company_id'], unique=False)
    op.create_table('document',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('current_version_id', sa.Uuid(), nullable=True),
    sa.Column('bucket_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('uploaded', 'pending_approval', 'action_required', 'verified', 'submitted', 'overdue', 'archived', name='document_status_enum'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('doc_type', sa.String(length=255), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['bucket_id'], ['bucket.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['company_admin.id'], ),
    sa.ForeignKeyConstraint(['current_version_id'], ['document_version.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_company_id'), 'document', ['company_id'], unique=False)
    op.create_table('document_access_override',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('principal', sa.String(length=255), nullable=False),
    sa.Column('permission_level', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_access_override_document_id'), 'document_access_override', ['document_id'], unique=False)
    op.create_table('document_version',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('encrypted_dek', sa.String(length=512), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['company_admin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_version_document_id'), 'document_version', ['document_id'], unique=False)
    op.drop_constraint('company_admin_email_key', 'company_admin', type_='unique')
    op.drop_index('ix_company_admin_email', table_name='company_admin')
    op.create_index(op.f('ix_company_admin_email'), 'company_admin', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_admin_email'), table_name='company_admin')
    op.create_index('ix_company_admin_email', 'company_admin', ['email'], unique=False)
    op.create_unique_constraint('company_admin_email_key', 'company_admin', ['email'])
    op.drop_index(op.f('ix_document_version_document_id'), table_name='document_version')
    op.drop_table('document_version')
    op.drop_index(op.f('ix_document_access_override_document_id'), table_name='document_access_override')
    op.drop_table('document_access_override')
    op.drop_index(op.f('ix_document_company_id'), table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('ix_bucket_company_id'), table_name='bucket')
    op.drop_table('bucket')
    # ### end Alembic commands ###
