"""Add SecretarialEase models

Revision ID: 9e4acaaff626
Revises: b94d6349b59b
Create Date: 2026-07-08 12:01:03.021713
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '9e4acaaff626'
down_revision: Union[str, None] = 'b94d6349b59b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_type',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('template_file_id', sa.Uuid(), nullable=True),
    sa.Column('metadata_schema', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_file_id'], ['document.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_type_company_id'), 'document_type', ['company_id'], unique=False)
    op.create_table('meeting_record',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('doc_type_id', sa.Uuid(), nullable=False),
    sa.Column('structured_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('linked_document_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['doc_type_id'], ['document_type.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['linked_document_id'], ['document.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_record_company_id'), 'meeting_record', ['company_id'], unique=False)
    op.create_index(op.f('ix_meeting_record_doc_type_id'), 'meeting_record', ['doc_type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meeting_record_doc_type_id'), table_name='meeting_record')
    op.drop_index(op.f('ix_meeting_record_company_id'), table_name='meeting_record')
    op.drop_table('meeting_record')
    op.drop_index(op.f('ix_document_type_company_id'), table_name='document_type')
    op.drop_table('document_type')
    # ### end Alembic commands ###
