"""Add Phase 2 AuditEase models

Revision ID: b94d6349b59b
Revises: 7d5c9bc40367
Create Date: 2026-07-08 11:43:28.678596
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b94d6349b59b'
down_revision: Union[str, None] = '7d5c9bc40367'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditor',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditor_email'), 'auditor', ['email'], unique=True)
    op.create_table('ledger_group',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('schedule_iii_category', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['ledger_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_engagement',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('period_label', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_engagement_company_id'), 'audit_engagement', ['company_id'], unique=False)
    op.create_table('ledger',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ledger_code', sa.String(), nullable=True),
    sa.Column('ledger_name', sa.String(), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('debit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('closing_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=True),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['group_id'], ['ledger_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_company_id'), 'ledger', ['company_id'], unique=False)
    op.create_table('report_template',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('json_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_template_company_id'), 'report_template', ['company_id'], unique=False)
    op.create_table('audit_entry',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('engagement_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['auditor.id'], ),
    sa.ForeignKeyConstraint(['engagement_id'], ['audit_engagement.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_entry_company_id'), 'audit_entry', ['company_id'], unique=False)
    op.create_table('auditor_engagement_grant',
    sa.Column('auditor_id', sa.Uuid(), nullable=False),
    sa.Column('engagement_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['auditor_id'], ['auditor.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['engagement_id'], ['audit_engagement.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('auditor_id', 'engagement_id')
    )
    op.create_table('auditor_invite',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('engagement_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['audit_engagement.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditor_invite_email'), 'auditor_invite', ['email'], unique=False)
    op.create_index(op.f('ix_auditor_invite_token'), 'auditor_invite', ['token'], unique=True)
    op.create_table('audit_entry_line',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entry_id', sa.Uuid(), nullable=False),
    sa.Column('ledger_id', sa.Uuid(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['entry_id'], ['audit_entry.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ledger_id'], ['ledger.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_entry_line_company_id'), 'audit_entry_line', ['company_id'], unique=False)
    op.create_foreign_key(None, 'document', 'document_version', ['current_version_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document', type_='foreignkey')
    op.drop_index(op.f('ix_audit_entry_line_company_id'), table_name='audit_entry_line')
    op.drop_table('audit_entry_line')
    op.drop_index(op.f('ix_auditor_invite_token'), table_name='auditor_invite')
    op.drop_index(op.f('ix_auditor_invite_email'), table_name='auditor_invite')
    op.drop_table('auditor_invite')
    op.drop_table('auditor_engagement_grant')
    op.drop_index(op.f('ix_audit_entry_company_id'), table_name='audit_entry')
    op.drop_table('audit_entry')
    op.drop_index(op.f('ix_report_template_company_id'), table_name='report_template')
    op.drop_table('report_template')
    op.drop_index(op.f('ix_ledger_company_id'), table_name='ledger')
    op.drop_table('ledger')
    op.drop_index(op.f('ix_audit_engagement_company_id'), table_name='audit_engagement')
    op.drop_table('audit_engagement')
    op.drop_table('ledger_group')
    op.drop_index(op.f('ix_auditor_email'), table_name='auditor')
    op.drop_table('auditor')
    # ### end Alembic commands ###
